### PR TITLE
Update hackney

### PR DESCRIPTION
**Pull request by tshakah**
I also took the opportunity to update other deps, but not the base Elixir requirements.

Closes https://github.com/flexibility-org/kernel/issues/1421

### CODE REVIEW

**Comment by giddie** [comment]
Has anything been done upstream, or is it similarly out-of-date?

**Comment by tshakah** [comment]
Upstream doesn't list Hackney as an explicit dependency. Indirectly it is on 1.6.1

**Comment by giddie** [comment]
Any idea why it is an explicit dependency in our fork? Maybe we can simply remove it to avoid getting out of date again?

**Comment by tshakah** [comment]
Yes, it's needed for https://hexdocs.pm/tesla/Tesla.Adapter.Hackney.html

**Comment by tshakah** [comment]
Which is explicitly called in the library: `client = Tesla.client(middlewares, Tesla.Adapter.Hackney)`

(line 129 of `http.ex`)

**Comment by giddie** [comment]
OK, so if Tesla doesn't require `hackney` itself, I wonder if we can pin the major version number instead of the minor? I'm guessing nothing's going to break unless Hackney makes a public API change that requires a major version number change. What do you think?

**Comment by tshakah** [comment]
Yeah, it's post 1.0, so that should be fine

**Comment by tshakah** [comment]
Although I don't know how library pins work - if it has 1.18 in the library lockfile, will that stop us upgrading in the future anyway?

**Comment by giddie** [comment]
It looks like the lockfile won't be a problem:

https://hexdocs.pm/elixir/1.12/library-guidelines.html#dependency-handling

**Pull request merged**
